//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitest.ADOmodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CualidMotivDeportiv
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CualidMotivDeportiv()
        {
            this.SujetosEvaluados = new HashSet<SujetosEvaluados>();
        }
    
        public long idTest { get; set; }
        public string DuraPru { get; set; }
        public string Fecha { get; set; }
        public string motivLogro { get; set; }
        public string noMotivLogro { get; set; }
        public string motivIntrínseca { get; set; }
        public string motivExtrínseca { get; set; }
        public string expecExito { get; set; }
        public string expecEficacia { get; set; }
        public string motivAproExito { get; set; }
        public string movEvitarFracaso { get; set; }
        public string motivMater { get; set; }
        public string motivRecono { get; set; }
        public string motivAutoDeportiva { get; set; }
        public string motivAutoPersono { get; set; }
        public string motivSuprain { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SujetosEvaluados> SujetosEvaluados { get; set; }
    }
}
