//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitest.ADOmodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Iped
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Iped()
        {
            this.SujetosEvaluados = new HashSet<SujetosEvaluados>();
        }
    
        public long idTest { get; set; }
        public string Fecha { get; set; }
        public string DuraPru { get; set; }
        public string Autoconfianza { get; set; }
        public string ContAfronNegativ { get; set; }
        public string ContAtencional { get; set; }
        public string ContVisuoimag { get; set; }
        public string NivelMotiv { get; set; }
        public string ContAfrontPositiv { get; set; }
        public string ContActitudinal { get; set; }
        public string calFinal { get; set; }
        public string calAutoConfianza { get; set; }
        public string calContAfrontNega { get; set; }
        public string calContAten { get; set; }
        public string calContVisuo { get; set; }
        public string calNivelMot { get; set; }
        public string calContAfroPos { get; set; }
        public string calContActitud { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SujetosEvaluados> SujetosEvaluados { get; set; }
    }
}
