//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitest.ADOmodel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mainEntities : DbContext
    {
        public mainEntities()
            : base("name=mainEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActitudAnteCompetencia> ActitudAnteCompetencia { get; set; }
        public virtual DbSet<AnsiedadCompetitiva> AnsiedadCompetitiva { get; set; }
        public virtual DbSet<CualidMotivDeportiv> CualidMotivDeportiv { get; set; }
        public virtual DbSet<CualiVolitivasDep> CualiVolitivasDep { get; set; }
        public virtual DbSet<DatosSujetos> DatosSujetos { get; set; }
        public virtual DbSet<Idetem> Idetem { get; set; }
        public virtual DbSet<Iped> Iped { get; set; }
        public virtual DbSet<MotivDeporButt> MotivDeporButt { get; set; }
        public virtual DbSet<Pru16pf> Pru16pf { get; set; }
        public virtual DbSet<PruCatell> PruCatell { get; set; }
        public virtual DbSet<PruCleaver> PruCleaver { get; set; }
        public virtual DbSet<PruDomino> PruDomino { get; set; }
        public virtual DbSet<PruEysenk> PruEysenk { get; set; }
        public virtual DbSet<PruFHumano> PruFHumano { get; set; }
        public virtual DbSet<PruIdareRago> PruIdareRago { get; set; }
        public virtual DbSet<PruIdareSituacional> PruIdareSituacional { get; set; }
        public virtual DbSet<PruLoehr> PruLoehr { get; set; }
        public virtual DbSet<PruPoms> PruPoms { get; set; }
        public virtual DbSet<PruRaven> PruRaven { get; set; }
        public virtual DbSet<PruResanti> PruResanti { get; set; }
        public virtual DbSet<PruTrcomple> PruTrcomple { get; set; }
        public virtual DbSet<PruTRN> PruTRN { get; set; }
        public virtual DbSet<PruTrsimple> PruTrsimple { get; set; }
        public virtual DbSet<PruWeil> PruWeil { get; set; }
        public virtual DbSet<SujetosEvaluados> SujetosEvaluados { get; set; }
        public virtual DbSet<Switchboard_Items> Switchboard_Items { get; set; }
        public virtual DbSet<Tipoetapa> Tipoetapa { get; set; }
    }
}
