//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitest.ADOmodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PruCleaver
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PruCleaver()
        {
            this.SujetosEvaluados = new HashSet<SujetosEvaluados>();
        }
    
        public long idTest { get; set; }
        public string DuraPru { get; set; }
        public string PuntajeFDM { get; set; }
        public string PuntajeFIM { get; set; }
        public string PuntajeFSM { get; set; }
        public string PuntajeFCM { get; set; }
        public string PuntajeFDL { get; set; }
        public string PuntajeFIL { get; set; }
        public string PuntajeFSL { get; set; }
        public string PuntajeFCL { get; set; }
        public string PuntajeTD { get; set; }
        public string PuntajeTI { get; set; }
        public string PuntajeTS { get; set; }
        public string PuntajeTC { get; set; }
        public string Validez { get; set; }
        public string Fecha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SujetosEvaluados> SujetosEvaluados { get; set; }
    }
}
