//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitest.ADOmodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PruCatell
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PruCatell()
        {
            this.SujetosEvaluados = new HashSet<SujetosEvaluados>();
        }
    
        public long idTest { get; set; }
        public string DuraPru { get; set; }
        public string PBrutaLatQ3 { get; set; }
        public string PBrutaLatC { get; set; }
        public string PBrutaLatL { get; set; }
        public string PBrutaLatO { get; set; }
        public string PBrutaLatQ4 { get; set; }
        public string PBrutaManQ3 { get; set; }
        public string PBrutaManC { get; set; }
        public string PBrutaManL { get; set; }
        public string PBrutaManO { get; set; }
        public string PBrutaManQ4 { get; set; }
        public string PBrutaTotal { get; set; }
        public string PBrutaLatManQ3 { get; set; }
        public string PBrutaLaManC { get; set; }
        public string PBrutaLatManL { get; set; }
        public string PBrutaLatManO { get; set; }
        public string PBrutaLatManQ4 { get; set; }
        public string PStensLatQ3 { get; set; }
        public string PStensLatC { get; set; }
        public string PStensLatL { get; set; }
        public string PStensLatO { get; set; }
        public string PStensLatQ4 { get; set; }
        public string PStensManQ3 { get; set; }
        public string PStensManC { get; set; }
        public string PStensManL { get; set; }
        public string PStensManO { get; set; }
        public string PStensManQ4 { get; set; }
        public string PStensLatManQ3 { get; set; }
        public string PStensLatManC { get; set; }
        public string PStensLatManL { get; set; }
        public string PStensLatManO { get; set; }
        public string PStensLatManQ4 { get; set; }
        public string PStensTotal { get; set; }
        public string IntSico { get; set; }
        public string PuntTotalLE { get; set; }
        public string Fecha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SujetosEvaluados> SujetosEvaluados { get; set; }
    }
}
