//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitest.ADOmodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PruResanti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PruResanti()
        {
            this.SujetosEvaluados = new HashSet<SujetosEvaluados>();
        }
    
        public long idTest { get; set; }
        public string Programa { get; set; }
        public string Manual { get; set; }
        public string Media { get; set; }
        public string Mediana { get; set; }
        public string Moda { get; set; }
        public string DesvStandar { get; set; }
        public string CoefVar { get; set; }
        public string Calificacion { get; set; }
        public string Media15 { get; set; }
        public string Mediana15 { get; set; }
        public string DesvStandar15 { get; set; }
        public string CoefVar15 { get; set; }
        public string Media2 { get; set; }
        public string Mediana2 { get; set; }
        public string DesvStandar2 { get; set; }
        public string CoefVar2 { get; set; }
        public string Media25 { get; set; }
        public string Mediana25 { get; set; }
        public string DesvStandar25 { get; set; }
        public string CoefVar25 { get; set; }
        public string Media3 { get; set; }
        public string Mediana3 { get; set; }
        public string DesvStandar3 { get; set; }
        public string CoefVar3 { get; set; }
        public string Tiempo1 { get; set; }
        public string Resultado1 { get; set; }
        public string Resultado2 { get; set; }
        public string Tiempo2 { get; set; }
        public string Resultado3 { get; set; }
        public string Tiempo3 { get; set; }
        public string Resultado4 { get; set; }
        public string Tiempo4 { get; set; }
        public string Resultado5 { get; set; }
        public string Tiempo5 { get; set; }
        public string Resultado6 { get; set; }
        public string Tiempo6 { get; set; }
        public string Resultado7 { get; set; }
        public string Tiempo7 { get; set; }
        public string Resultado8 { get; set; }
        public string Tiempo8 { get; set; }
        public string Resultado9 { get; set; }
        public string Tiempo9 { get; set; }
        public string Resultado10 { get; set; }
        public string Tiempo10 { get; set; }
        public string Resultado11 { get; set; }
        public string Tiempo11 { get; set; }
        public string Resultado12 { get; set; }
        public string Tiempo12 { get; set; }
        public string Resultado13 { get; set; }
        public string Tiempo13 { get; set; }
        public string Resultado14 { get; set; }
        public string Tiempo14 { get; set; }
        public string Resultado15 { get; set; }
        public string Tiempo15 { get; set; }
        public string Resultado16 { get; set; }
        public string Tiempo16 { get; set; }
        public string Resultado17 { get; set; }
        public string Tiempo17 { get; set; }
        public string Resultado18 { get; set; }
        public string Tiempo18 { get; set; }
        public string Resultado19 { get; set; }
        public string Tiempo19 { get; set; }
        public string Resultado20 { get; set; }
        public string Tiempo20 { get; set; }
        public string Fecha { get; set; }
        public string Moda15 { get; set; }
        public string Moda2 { get; set; }
        public string Moda25 { get; set; }
        public string Moda3 { get; set; }
        public string VariantVelo1 { get; set; }
        public string VariantVelo2 { get; set; }
        public string VariantVelo3 { get; set; }
        public string VariantVelo4 { get; set; }
        public string VariantVelo5 { get; set; }
        public string VariantVelo6 { get; set; }
        public string VariantVelo7 { get; set; }
        public string VariantVelo8 { get; set; }
        public string VariantVelo9 { get; set; }
        public string VariantVelo10 { get; set; }
        public string VariantVelo11 { get; set; }
        public string VariantVelo12 { get; set; }
        public string VariantVelo13 { get; set; }
        public string VariantVelo14 { get; set; }
        public string VariantVelo15 { get; set; }
        public string VariantVelo16 { get; set; }
        public string VariantVelo17 { get; set; }
        public string VariantVelo18 { get; set; }
        public string VariantVelo19 { get; set; }
        public string VariantVelo20 { get; set; }
        public string DiferenciaTiempo1 { get; set; }
        public string DiferenciaTiempo2 { get; set; }
        public string DiferenciaTiempo3 { get; set; }
        public string DiferenciaTiempo4 { get; set; }
        public string DiferenciaTiempo5 { get; set; }
        public string DiferenciaTiempo6 { get; set; }
        public string DiferenciaTiempo7 { get; set; }
        public string DiferenciaTiempo8 { get; set; }
        public string DiferenciaTiempo9 { get; set; }
        public string DiferenciaTiempo10 { get; set; }
        public string DiferenciaTiempo11 { get; set; }
        public string DiferenciaTiempo12 { get; set; }
        public string DiferenciaTiempo13 { get; set; }
        public string DiferenciaTiempo14 { get; set; }
        public string DiferenciaTiempo15 { get; set; }
        public string DiferenciaTiempo16 { get; set; }
        public string DiferenciaTiempo17 { get; set; }
        public string DiferenciaTiempo18 { get; set; }
        public string DiferenciaTiempo19 { get; set; }
        public string DiferenciaTiempo20 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SujetosEvaluados> SujetosEvaluados { get; set; }
    }
}
