//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitest.ADOmodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PruRaven
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PruRaven()
        {
            this.SujetosEvaluados = new HashSet<SujetosEvaluados>();
        }
    
        public long idTest { get; set; }
        public string DuraPru { get; set; }
        public string PuntajeTotal { get; set; }
        public string PuntajeA { get; set; }
        public string PuntajeB { get; set; }
        public string PuntajeC { get; set; }
        public string PuntajeD { get; set; }
        public string PuntajeE { get; set; }
        public string Porcentaje { get; set; }
        public string Rango { get; set; }
        public string Diagnostico { get; set; }
        public string Fecha { get; set; }
        public string Consistencia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SujetosEvaluados> SujetosEvaluados { get; set; }
    }
}
