//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitest.ADOmodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PruTrcomple
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PruTrcomple()
        {
            this.SujetosEvaluados = new HashSet<SujetosEvaluados>();
            this.SujetosEvaluados1 = new HashSet<SujetosEvaluados>();
        }
    
        public long idTest { get; set; }
        public string Sonido { get; set; }
        public string CantEstimulos { get; set; }
        public string Variante { get; set; }
        public string TiempoMaximo { get; set; }
        public string TiempoMinimo { get; set; }
        public string SumTiempo { get; set; }
        public string RespCorrecta { get; set; }
        public string TiempoMedio { get; set; }
        public string DesvStandar { get; set; }
        public string CoefVariacion { get; set; }
        public string CantOmisiones { get; set; }
        public string Canterrores { get; set; }
        public string Canterroresson { get; set; }
        public string Estimulo1 { get; set; }
        public string Respuesta1 { get; set; }
        public string Tiempo1 { get; set; }
        public string Estimulo2 { get; set; }
        public string Respuesta2 { get; set; }
        public string Tiempo2 { get; set; }
        public string Estimulo3 { get; set; }
        public string Respuesta3 { get; set; }
        public string Tiempo3 { get; set; }
        public string Estimulo4 { get; set; }
        public string Respuesta4 { get; set; }
        public string Tiempo4 { get; set; }
        public string Estimulo5 { get; set; }
        public string Respuesta5 { get; set; }
        public string Tiempo5 { get; set; }
        public string Estimulo6 { get; set; }
        public string Respuesta6 { get; set; }
        public string Tiempo6 { get; set; }
        public string Estimulo7 { get; set; }
        public string Respuesta7 { get; set; }
        public string Tiempo7 { get; set; }
        public string Estimulo8 { get; set; }
        public string Respuesta8 { get; set; }
        public string Tiempo8 { get; set; }
        public string Estimulo9 { get; set; }
        public string Respuesta9 { get; set; }
        public string Tiempo9 { get; set; }
        public string Estimulo10 { get; set; }
        public string Respuesta10 { get; set; }
        public string Tiempo10 { get; set; }
        public string Estimulo11 { get; set; }
        public string Respuesta11 { get; set; }
        public string Tiempo11 { get; set; }
        public string Estimulo12 { get; set; }
        public string Respuesta12 { get; set; }
        public string Tiempo12 { get; set; }
        public string Estimulo13 { get; set; }
        public string Respuesta13 { get; set; }
        public string Tiempo13 { get; set; }
        public string Estimulo14 { get; set; }
        public string Respuesta14 { get; set; }
        public string Tiempo14 { get; set; }
        public string Estimulo15 { get; set; }
        public string Respuesta15 { get; set; }
        public string Tiempo15 { get; set; }
        public string Estimulo16 { get; set; }
        public string Respuesta16 { get; set; }
        public string Tiempo16 { get; set; }
        public string Estimulo17 { get; set; }
        public string Respuesta17 { get; set; }
        public string Tiempo17 { get; set; }
        public string Estimulo18 { get; set; }
        public string Respuesta18 { get; set; }
        public string Tiempo18 { get; set; }
        public string Estimulo19 { get; set; }
        public string Respuesta19 { get; set; }
        public string Tiempo19 { get; set; }
        public string Estimulo20 { get; set; }
        public string Respuesta20 { get; set; }
        public string Tiempo20 { get; set; }
        public string Estimulo21 { get; set; }
        public string Respuesta21 { get; set; }
        public string Tiempo21 { get; set; }
        public string Estimulo22 { get; set; }
        public string Respuesta22 { get; set; }
        public string Tiempo22 { get; set; }
        public string Estimulo23 { get; set; }
        public string Respuesta23 { get; set; }
        public string Tiempo23 { get; set; }
        public string Estimulo24 { get; set; }
        public string Respuesta24 { get; set; }
        public string Tiempo24 { get; set; }
        public string Estimulo25 { get; set; }
        public string Respuesta25 { get; set; }
        public string Tiempo25 { get; set; }
        public string Estimulo26 { get; set; }
        public string Respuesta26 { get; set; }
        public string Tiempo26 { get; set; }
        public string Estimulo27 { get; set; }
        public string Respuesta27 { get; set; }
        public string Tiempo27 { get; set; }
        public string Estimulo28 { get; set; }
        public string Respuesta28 { get; set; }
        public string Tiempo28 { get; set; }
        public string Estimulo29 { get; set; }
        public string Respuesta29 { get; set; }
        public string Tiempo29 { get; set; }
        public string Estimulo30 { get; set; }
        public string Respuesta30 { get; set; }
        public string Tiempo30 { get; set; }
        public string Fecha { get; set; }
        public string CantErrorColor { get; set; }
        public string CantRespAdelant { get; set; }
        public string Sonido1 { get; set; }
        public string Sonido2 { get; set; }
        public string Sonido3 { get; set; }
        public string Sonido4 { get; set; }
        public string Sonido5 { get; set; }
        public string Sonido6 { get; set; }
        public string Sonido7 { get; set; }
        public string Sonido8 { get; set; }
        public string Sonido9 { get; set; }
        public string Sonido10 { get; set; }
        public string Sonido11 { get; set; }
        public string Sonido12 { get; set; }
        public string Sonido13 { get; set; }
        public string Sonido14 { get; set; }
        public string Sonido15 { get; set; }
        public string Sonido16 { get; set; }
        public string Sonido17 { get; set; }
        public string Sonido18 { get; set; }
        public string Sonido19 { get; set; }
        public string Sonido20 { get; set; }
        public string Sonido21 { get; set; }
        public string Sonido22 { get; set; }
        public string Sonido23 { get; set; }
        public string Sonido24 { get; set; }
        public string Sonido25 { get; set; }
        public string Sonido26 { get; set; }
        public string Sonido27 { get; set; }
        public string Sonido28 { get; set; }
        public string Sonido29 { get; set; }
        public string Sonido30 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SujetosEvaluados> SujetosEvaluados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SujetosEvaluados> SujetosEvaluados1 { get; set; }
    }
}
