//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitest.ADOmodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PruTrsimple
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PruTrsimple()
        {
            this.SujetosEvaluados = new HashSet<SujetosEvaluados>();
        }
    
        public long idTest { get; set; }
        public string CantEstimulos { get; set; }
        public string TiempoMaximo { get; set; }
        public string TiempoMinimo { get; set; }
        public string SumTiempo { get; set; }
        public string RespCorrecta { get; set; }
        public string TiempoMedio { get; set; }
        public string DesvStandar { get; set; }
        public string CoefVariacion { get; set; }
        public string CantOmisiones { get; set; }
        public string Tiempo1 { get; set; }
        public string Tiempo2 { get; set; }
        public string Tiempo3 { get; set; }
        public string Tiempo4 { get; set; }
        public string Tiempo5 { get; set; }
        public string Tiempo6 { get; set; }
        public string Tiempo7 { get; set; }
        public string Tiempo8 { get; set; }
        public string Tiempo9 { get; set; }
        public string Tiempo10 { get; set; }
        public string Tiempo11 { get; set; }
        public string Tiempo12 { get; set; }
        public string Tiempo13 { get; set; }
        public string Tiempo14 { get; set; }
        public string Tiempo15 { get; set; }
        public string Tiempo16 { get; set; }
        public string Tiempo17 { get; set; }
        public string Tiempo18 { get; set; }
        public string Tiempo19 { get; set; }
        public string Tiempo20 { get; set; }
        public string Tiempo21 { get; set; }
        public string Tiempo22 { get; set; }
        public string Tiempo23 { get; set; }
        public string Tiempo24 { get; set; }
        public string Tiempo25 { get; set; }
        public string Tiempo26 { get; set; }
        public string Tiempo27 { get; set; }
        public string Tiempo28 { get; set; }
        public string Tiempo29 { get; set; }
        public string Tiempo30 { get; set; }
        public string Fecha { get; set; }
        public string DuraPru { get; set; }
        public string CantAdel { get; set; }
        public string TipoEstimulo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SujetosEvaluados> SujetosEvaluados { get; set; }
    }
}
