//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitest.ADOmodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PruTRN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PruTRN()
        {
            this.SujetosEvaluados = new HashSet<SujetosEvaluados>();
        }
    
        public long idTest { get; set; }
        public string Variante { get; set; }
        public string Calificacion { get; set; }
        public string CantResp { get; set; }
        public string Resultado1 { get; set; }
        public string Resultado2 { get; set; }
        public string Resultado3 { get; set; }
        public string Resultado4 { get; set; }
        public string Resultado5 { get; set; }
        public string Resultado6 { get; set; }
        public string Resultado7 { get; set; }
        public string Resultado8 { get; set; }
        public string Resultado9 { get; set; }
        public string Resultado10 { get; set; }
        public string Resultado11 { get; set; }
        public string Resultado12 { get; set; }
        public string Resultado13 { get; set; }
        public string Resultado14 { get; set; }
        public string Resultado15 { get; set; }
        public string Resultado16 { get; set; }
        public string Resultado17 { get; set; }
        public string Resultado18 { get; set; }
        public string Resultado19 { get; set; }
        public string Resultado20 { get; set; }
        public string Resultado21 { get; set; }
        public string Resultado22 { get; set; }
        public string Resultado23 { get; set; }
        public string Resultado24 { get; set; }
        public string Resultado25 { get; set; }
        public string Resultado26 { get; set; }
        public string Resultado27 { get; set; }
        public string Resultado28 { get; set; }
        public string Resultado29 { get; set; }
        public string Resultado30 { get; set; }
        public string Resultado31 { get; set; }
        public string Resultado32 { get; set; }
        public string Resultado33 { get; set; }
        public string Resultado34 { get; set; }
        public string Resultado35 { get; set; }
        public string Resultado36 { get; set; }
        public string Resultado37 { get; set; }
        public string Resultado38 { get; set; }
        public string Resultado39 { get; set; }
        public string Resultado40 { get; set; }
        public string Resultado41 { get; set; }
        public string Resultado42 { get; set; }
        public string Resultado43 { get; set; }
        public string Resultado44 { get; set; }
        public string Resultado45 { get; set; }
        public string Resultado46 { get; set; }
        public string Resultado47 { get; set; }
        public string Resultado48 { get; set; }
        public string Resultado49 { get; set; }
        public string NRepeticiones { get; set; }
        public string NSaltos { get; set; }
        public string CdRect { get; set; }
        public string CdNoRect { get; set; }
        public string Cambcolor { get; set; }
        public string Duracion { get; set; }
        public string Fecha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SujetosEvaluados> SujetosEvaluados { get; set; }
    }
}
