//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitest.ADOmodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SujetosEvaluados
    {
        public long idSujetoEvaluado { get; set; }
        public Nullable<long> idSujeto { get; set; }
        public string Fecha { get; set; }
        public Nullable<long> Etapa { get; set; }
        public Nullable<long> PIdareSitua { get; set; }
        public Nullable<long> P16pf { get; set; }
        public Nullable<long> PEpi { get; set; }
        public Nullable<long> PRaven { get; set; }
        public Nullable<long> PDomino { get; set; }
        public Nullable<long> PCleaver { get; set; }
        public Nullable<long> PFactorHum { get; set; }
        public Nullable<long> PCatell { get; set; }
        public Nullable<long> PWeil { get; set; }
        public Nullable<long> PTrsimple { get; set; }
        public Nullable<long> PTrcomple { get; set; }
        public Nullable<long> PTrcomples { get; set; }
        public Nullable<long> PResanti { get; set; }
        public Nullable<long> PTRN { get; set; }
        public Nullable<long> PPoms { get; set; }
        public Nullable<long> PLoehr { get; set; }
        public Nullable<long> PEysenk { get; set; }
        public Nullable<long> PActiAnteComp { get; set; }
        public Nullable<long> PCualidMotivDepor { get; set; }
        public Nullable<long> PMotivDepButt { get; set; }
        public Nullable<long> PIped { get; set; }
        public Nullable<long> PIdetem { get; set; }
        public Nullable<long> PCualiVolitiv { get; set; }
        public Nullable<long> PIdareRasgo { get; set; }
        public Nullable<long> PAnsiedadCompetitiva { get; set; }
    
        public virtual ActitudAnteCompetencia ActitudAnteCompetencia { get; set; }
        public virtual AnsiedadCompetitiva AnsiedadCompetitiva { get; set; }
        public virtual CualidMotivDeportiv CualidMotivDeportiv { get; set; }
        public virtual CualiVolitivasDep CualiVolitivasDep { get; set; }
        public virtual DatosSujetos DatosSujetos { get; set; }
        public virtual Idetem Idetem { get; set; }
        public virtual Iped Iped { get; set; }
        public virtual MotivDeporButt MotivDeporButt { get; set; }
        public virtual Pru16pf Pru16pf { get; set; }
        public virtual PruCatell PruCatell { get; set; }
        public virtual PruCleaver PruCleaver { get; set; }
        public virtual PruDomino PruDomino { get; set; }
        public virtual PruEysenk PruEysenk { get; set; }
        public virtual PruFHumano PruFHumano { get; set; }
        public virtual PruIdareRago PruIdareRago { get; set; }
        public virtual PruIdareSituacional PruIdareSituacional { get; set; }
        public virtual PruLoehr PruLoehr { get; set; }
        public virtual PruPoms PruPoms { get; set; }
        public virtual PruRaven PruRaven { get; set; }
        public virtual PruResanti PruResanti { get; set; }
        public virtual PruTrcomple PruTrcomple { get; set; }
        public virtual PruTrcomple PruTrcomple1 { get; set; }
        public virtual PruTRN PruTRN { get; set; }
        public virtual PruTrsimple PruTrsimple { get; set; }
        public virtual PruWeil PruWeil { get; set; }
        public virtual Tipoetapa Tipoetapa { get; set; }
    }
}
