//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitest.ADOmodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Switchboard_Items
    {
        public long SwitchboardID { get; set; }
        public long ItemNumber { get; set; }
        public string ItemText { get; set; }
        public Nullable<long> Command { get; set; }
        public string Argument { get; set; }
    }
}
